# much of this is taken from the Empress main.yml file and the Gemelli main.yml
name: Main CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download Q2 file
        run: wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: q2
          environment-file: qiime2-latest-py36-linux-conda.yml

      - name: Install conda reqs
        shell: bash -l {0}
        run: conda install --file ci/conda_requirements.txt -c biocore

      - name: Install auxillary CI packages
        shell: bash -l {0}
        run: conda install -c conda-forge -c bioconda coveralls flake8 nose r-devtools
      
      - name: Install R-SCRuB
        shell: bash -l {0}
        run: Rscript -e 'install.packages(c("cli","pkgload"), repos = "http://cran.us.r-project.org"); devtools::install_github("korem-lab/SCRuB"); torch::install_torch()'

      - name: Install q2-SCRuB
        shell: bash -l {0}
        run: pip install -e .

      - name: Check style
        shell: bash -l {0}
        run: flake8 q2_SCRuB/*.py q2_SCRuB/tests/*.py setup.py

      - name: Run tests & coverage
        shell: bash -l {0}
        run: nosetests -v q2_SCRuB --with-coverage --cover-package=q2_SCRuB

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#     - name: checkout source
#       uses: actions/checkout@v2

#     - name: set up python 3.8
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.8

#     - name: install dependencies
#       run: python -m pip install --upgrade pip

#     - name: lint
#       run: |
#         pip install -q https://github.com/qiime2/q2lint/archive/master.zip
#         q2lint
#         pip install -q flake8
# #         flake8
#   build-and-test:
#     needs: lint
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#     - name: checkout source
#       uses: actions/checkout@v2
#       with:
#         fetch-depth: 0

# #     - name: set up git repo for versioneer
# #       run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

#     - uses: qiime2/action-library-packaging@alpha1
#       with:
#         package-name: q2-scrub
#         build-target: dev
#         additional-tests: py.test --pyargs q2_SCRuB
#         library-token: ${{ secrets.LIBRARY_TOKEN }}
